apiVersion: v1
kind: Service
metadata:
  name: bike-showroom-service
  labels:
    app: bike-showroom
spec:
  type: NodePort
  selector:
    app: bike-showroom
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30080
